Class {
	#name : #DepEdge,
	#superclass : #Object,
	#instVars : [
		'x',
		'y',
		'zs'
	],
	#category : #'MachineArithmetic-Refinement'
}

{ #category : #accessing }
DepEdge >> x [
	^ x
]

{ #category : #accessing }
DepEdge >> x: anObject [
	x := anObject
]

{ #category : #accessing }
DepEdge >> y [
	^ y
]

{ #category : #accessing }
DepEdge >> y: anObject [
	y := anObject
]

{ #category : #accessing }
DepEdge >> zs [
	^ zs
]

{ #category : #accessing }
DepEdge >> zs: anObject [
	zs := anObject
]
