Extension { #name : #Character }

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> brokenBar [
	^self codePoint: 16rA6
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> centSign [
	^self codePoint: 16rA2
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> copyrightSign [
	^self codePoint: 16rA9
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> currencySign [
	^self codePoint: 16rA4
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> degreeSign [
	^self codePoint: 16rB0
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> diaeresis [
	^self codePoint: 16rA8
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> divisionSign [
	^self codePoint: 16rF7
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> feminineOrdinalIndicator [
	^self codePoint: 16rAA
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> invertedExclamationMark [
	^self codePoint: 16rA1
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> invertedQuestionMark [
	^self codePoint: 16rBF
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> leftPointingDoubleAngleQuotationMark [
	^self codePoint: 16rAB
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> macron [
	^self codePoint: 16rAF
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> masculineOrdinalIndicator [
	^self codePoint: 16rBA
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> microSign [
	^self codePoint: 16rB5
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> multiplicationSign [
	^self codePoint: 16rD7
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> notSign [
	^self codePoint: 16rAC
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> oneHalf [
	^self codePoint: 16rBD
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> oneQuarter [
	^self codePoint: 16rBC
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> pilcrowSign [
	^self codePoint: 16rB6
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> plusMinusSign [
	^self codePoint: 16rB1
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> poundSign [
	^self codePoint: 16rA3
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> registeredSign [
	^self codePoint: 16rAE
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> rightPointingDoubleAngleQuotationMark [
	^self codePoint: 16rBB
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> sectionSign [
	^self codePoint: 16rA7
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> softHyphen [
	^self codePoint: 16rAD
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> superscriptOne [
	^self codePoint: 16rB9
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> superscriptThree [
	^self codePoint: 16rB3
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> superscriptTwo [
	^self codePoint: 16rB2
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> threeQuarters [
	^self codePoint: 16rBE
]

{ #category : #'*MachineArithmetic-MathNotation' }
Character class >> yenSign [
	^self codePoint: 16rA5
]
